### ISSUE TITLE
Rails3, Rspec2: Remarkable couldn't mock_models

### ISSUE THREAD

**Issue by petRUShka** [remarkable-rb/remarkable#13]
time_table_controller_spec, line 23:

<pre>mock_models :post </pre>

Error in console:
<code><pre>
/home/petrushka/.bundle/ruby/svn/gems/remarkable-4.0.0.alpha4/lib/remarkable/core/macros.rb:15:in `method_missing': undefined method`mock_model' for :Class (NoMethodError)
    from /home/petrushka/webdev/my_app/spec/controllers/admin/timetable_controller_spec.rb:23:in `block (2 levels) in <top (required)>
</pre></code>

spec_helper: https://gist.github.com/1d92348b08b71a5fc798

ruby 1.9.3dev (2010-05-08 trunk 27674) [x86_64-linux]
spork (0.8.4)
Rails 3: beta3
Rspec2: beta11

**Comment by hosh** [comment]
I don't remember, but isn't mock_model part of Remarkable::Rails?

**Comment by petRUShka** [comment]
Yes. Please, look at: http://remarkable.rubyforge.org/rails/classes/Remarkable/ActionController/MacroStubs/ClassMethods.html#M000025

**Comment by hosh** [comment]
Right. 

Remarkable/Rails is _not_ implemented, mock_model will not work. The doc you are looking at is for Remarkable 3. Someone else may port over remarkable/rails, but I am not likely to port it because I don't have a need for it. 

Have you looked at Rspec let() and the new Rspec metadata?

This is an example of something I wrote with using pure Rspec 2: https://gist.github.com/741657dae42ae9706672

Think about it.

**Comment by petRUShka** [comment]
No, i haven't look for let. Thank you for direction, I will look at them!
